# Generated by Django 4.0 on 2021-12-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_id_hash',
            field=models.BinaryField(help_text='SHA256 hash of the CWA location ID', unique=True, verbose_name='Location ID Hash'),
        ),
    ]
