# Generated by Django 4.0 on 2022-01-03 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_location_id_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Used as unique identifier to clients', verbose_name='UUID'),
        ),
    ]
