# Generated by Django 4.0 on 2022-01-03 19:34
from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Location = apps.get_model('location', 'Location')
    for row in Location.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
