version: "3"

x-django-tbl: &django-tpl
  build: .
  restart: unless-stopped
  environment: &django-env-tpl
    DATABASE_URL: "postgres://cwa_notifier:changeme@db/cwa_notifier"
    CACHE_URL: "rediscache://redis"
    BROKER_URL: "amqp://rabbitmq"
    # TODO: customize the following ones
    SECRET_KEY: "django-insecure-t*m4njw77bnd-uotk$hbjfy+#cyu#e90hl=$v9^ybtx-572(0a" # python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
    ALLOWED_HOSTS: "localhost"
    TELEGRAM_TOKEN: ""
    CSRF_TRUSTED_ORIGINS: "http://localhost"
  depends_on:
    - db
    - rabbitmq
    - redis
  volumes:
    - ./data/packages:/usr/src/app/data/packages:rw
    - ./mediafiles:/usr/src/app/mediafiles:rw
    - staticfiles:/usr/src/app/staticfiles:rw

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "cwa_notifier"
      POSTGRES_USER: "cwa_notifier"
      POSTGRES_PASSWORD: "changeme"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    hostname: rabbitmq
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    restart: unless-stopped

  nginx:
    build: .deployment/nginx
    restart: unless-stopped
    volumes:
      - ./mediafiles:/var/www/html/media:ro
      - staticfiles:/var/www/html/static:ro
    ports:
      - "8000:80"
    depends_on:
      - web

  web:
    <<: *django-tpl
    environment:
      <<: *django-env-tpl
      DJANGO_MANAGEPY_MIGRATE: "on"

  worker:
    <<: *django-tpl
    command: "celery -A cwa_venue_notifier worker -B -E -Q celery -l INFO -s /tmp/celerybeat-schedule" # "-B" enables beat

  telegram:
    <<: *django-tpl
    command: "python manage.py start_polling"

volumes:
  staticfiles:
