# Generated by Django 4.0 on 2021-12-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraceWarningPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_version', models.IntegerField(help_text='Version of the API', verbose_name='API Version')),
                ('interval_number', models.BigIntegerField(help_text='Interval in 10 minute steps since UNIX epoch', verbose_name='Interval Number')),
                ('region', models.CharField(help_text="For example 'DE'", max_length=2, verbose_name='Region')),
                ('imported_at', models.DateTimeField(null=True)),
            ],
            options={
                'unique_together': {('api_version', 'interval_number', 'region')},
            },
        ),
        migrations.CreateModel(
            name='TraceTimeIntervalWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('location_id_hash', models.BinaryField(help_text='SHA256 hash of the location ID', verbose_name='Location ID Hash')),
                ('start_interval_number', models.BigIntegerField(help_text='Start interval in 10 minute steps since UNIX epoch', verbose_name='Start interval number')),
                ('period', models.BigIntegerField(help_text='Warning duration in 10 minute steps', verbose_name='Period')),
                ('transmission_risk_level', models.BigIntegerField(verbose_name='Transmission Risk Level')),
                ('package', models.ForeignKey(help_text='The warning package, where this time interval warning comes from', on_delete=django.db.models.deletion.CASCADE, to='warning.tracewarningpackage', verbose_name='Package')),
            ],
            options={
                'unique_together': {('package', 'position')},
            },
        ),
        migrations.CreateModel(
            name='CheckInProtectedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('location_id_hash', models.BinaryField(help_text='SHA256 hash of the location ID', verbose_name='Location ID Hash')),
                ('iv', models.BinaryField(verbose_name='IV')),
                ('encrypted_check_in_record', models.BinaryField(verbose_name='Encrypted Check-In Record')),
                ('mac', models.BinaryField(verbose_name='MAC')),
                ('package', models.ForeignKey(help_text='The warning package, where this protected check-in report comes from', on_delete=django.db.models.deletion.CASCADE, to='warning.tracewarningpackage', verbose_name='Package')),
            ],
            options={
                'unique_together': {('package', 'position')},
            },
        ),
    ]
