# Generated by Django 4.0 on 2021-12-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracewarningpackage',
            options={'ordering': ['-interval_number']},
        ),
    ]
