# Generated by Django 4.0 on 2021-12-26 00:14

from django.db import migrations, models
import django.db.models.deletion
import warning.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_location_id_hash'),
        ('warning', '0002_alter_tracewarningpackage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinprotectedreport',
            options={'ordering': ['-package', '-position']},
        ),
        migrations.AlterModelOptions(
            name='tracetimeintervalwarning',
            options={'ordering': ['-package', '-position']},
        ),
        migrations.AlterModelOptions(
            name='tracewarningpackage',
            options={'ordering': ['-interval_number', 'region', '-api_version']},
        ),
        migrations.AlterField(
            model_name='tracewarningpackage',
            name='imported_at',
            field=models.DateTimeField(null=True, verbose_name='Imported at'),
        ),
        migrations.AlterField(
            model_name='tracewarningpackage',
            name='interval_number',
            field=models.BigIntegerField(help_text='Interval in hours since UNIX epoch', verbose_name='Interval Number'),
        ),

        # this is a no-op operation, that tells django explicitly the db_column
        migrations.AlterField(
            model_name='checkinprotectedreport',
            name='location_id_hash',
            field=models.BinaryField(db_column='location_id_hash', help_text='SHA256 hash of the location ID', verbose_name='Location ID Hash')
        ),
        migrations.AlterField(
            model_name='tracetimeintervalwarning',
            name='location_id_hash',
            field=models.BinaryField(db_column='location_id_hash', help_text='SHA256 hash of the location ID', verbose_name='Location ID Hash'),
        ),

        # this is a no-op operation that tells django that the field name has changed, while the db_column stays unmodified
        migrations.RenameField(
            model_name='checkinprotectedreport',
            old_name='location_id_hash',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='tracetimeintervalwarning',
            old_name='location_id_hash',
            new_name='location',
        ),

        # finally, tell django that this field is now a ForeignKey without db constraint
        migrations.AlterField(
           model_name='checkinprotectedreport',
           name='location',
           field=warning.models.CustomForeignKey(db_column='location_id_hash', db_constraint=False, editable=False,
                                                 on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='location.location', to_field='location_id_hash'),
        ),
        migrations.AlterField(
            model_name='tracetimeintervalwarning',
            name='location',
            field=warning.models.CustomForeignKey(db_column='location_id_hash', db_constraint=False, editable=False,
                                                  on_delete=django.db.models.deletion.DO_NOTHING,
                                                  to='location.location', to_field='location_id_hash'),
        ),

        # make nearly everything editable=False
        migrations.AlterField(
            model_name='checkinprotectedreport',
            name='package',
            field=models.ForeignKey(editable=False,
                                    help_text='The warning package, where this protected check-in report comes from',
                                    on_delete=django.db.models.deletion.CASCADE, to='warning.tracewarningpackage',
                                    verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='checkinprotectedreport',
            name='position',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tracetimeintervalwarning',
            name='package',
            field=models.ForeignKey(editable=False,
                                    help_text='The warning package, where this time interval warning comes from',
                                    on_delete=django.db.models.deletion.CASCADE, to='warning.tracewarningpackage',
                                    verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='tracetimeintervalwarning',
            name='period',
            field=models.BigIntegerField(editable=False, help_text='Warning duration in 10 minute steps',
                                         verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='tracetimeintervalwarning',
            name='position',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tracetimeintervalwarning',
            name='start_interval_number',
            field=models.BigIntegerField(editable=False, help_text='Start interval in 10 minute steps since UNIX epoch',
                                         verbose_name='Start interval number'),
        ),
        migrations.AlterField(
            model_name='tracetimeintervalwarning',
            name='transmission_risk_level',
            field=models.BigIntegerField(editable=False, verbose_name='Transmission Risk Level'),
        ),
        migrations.AlterField(
            model_name='tracewarningpackage',
            name='api_version',
            field=models.IntegerField(editable=False, help_text='Version of the API', verbose_name='API Version'),
        ),
        migrations.AlterField(
            model_name='tracewarningpackage',
            name='interval_number',
            field=models.BigIntegerField(editable=False, help_text='Interval in hours since UNIX epoch',
                                         verbose_name='Interval Number'),
        ),
        migrations.AlterField(
            model_name='tracewarningpackage',
            name='region',
            field=models.CharField(editable=False, help_text="For example 'DE'", max_length=2, verbose_name='Region'),
        ),
    ]
