# Generated by Django 4.0 on 2021-12-25 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.BigIntegerField(help_text='Telegram chat', verbose_name='Chat ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Venue')),
            ],
            options={
                'verbose_name': 'Warning-Subscription',
                'verbose_name_plural': 'Warning-Subscriptions',
            },
        ),
    ]
