"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class CheckInRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STARTINTERVALNUMBER_FIELD_NUMBER: builtins.int
    PERIOD_FIELD_NUMBER: builtins.int
    TRANSMISSIONRISKLEVEL_FIELD_NUMBER: builtins.int
    startIntervalNumber: builtins.int = ...
    period: builtins.int = ...
    transmissionRiskLevel: builtins.int = ...
    def __init__(self,
        *,
        startIntervalNumber : builtins.int = ...,
        period : builtins.int = ...,
        transmissionRiskLevel : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["period",b"period","startIntervalNumber",b"startIntervalNumber","transmissionRiskLevel",b"transmissionRiskLevel"]) -> None: ...
global___CheckInRecord = CheckInRecord

class CheckInProtectedReport(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LOCATIONIDHASH_FIELD_NUMBER: builtins.int
    IV_FIELD_NUMBER: builtins.int
    ENCRYPTEDCHECKINRECORD_FIELD_NUMBER: builtins.int
    MAC_FIELD_NUMBER: builtins.int
    locationIdHash: builtins.bytes = ...
    iv: builtins.bytes = ...
    encryptedCheckInRecord: builtins.bytes = ...
    mac: builtins.bytes = ...
    def __init__(self,
        *,
        locationIdHash : builtins.bytes = ...,
        iv : builtins.bytes = ...,
        encryptedCheckInRecord : builtins.bytes = ...,
        mac : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["encryptedCheckInRecord",b"encryptedCheckInRecord","iv",b"iv","locationIdHash",b"locationIdHash","mac",b"mac"]) -> None: ...
global___CheckInProtectedReport = CheckInProtectedReport

class TraceWarningPackage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTERVALNUMBER_FIELD_NUMBER: builtins.int
    REGION_FIELD_NUMBER: builtins.int
    TIMEINTERVALWARNINGS_FIELD_NUMBER: builtins.int
    CHECKINPROTECTEDREPORTS_FIELD_NUMBER: builtins.int
    intervalNumber: builtins.int = ...
    """hours since UNIX Epoch"""

    region: typing.Text = ...
    @property
    def timeIntervalWarnings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraceTimeIntervalWarning]: ...
    @property
    def checkInProtectedReports(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CheckInProtectedReport]: ...
    def __init__(self,
        *,
        intervalNumber : builtins.int = ...,
        region : typing.Text = ...,
        timeIntervalWarnings : typing.Optional[typing.Iterable[global___TraceTimeIntervalWarning]] = ...,
        checkInProtectedReports : typing.Optional[typing.Iterable[global___CheckInProtectedReport]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["checkInProtectedReports",b"checkInProtectedReports","intervalNumber",b"intervalNumber","region",b"region","timeIntervalWarnings",b"timeIntervalWarnings"]) -> None: ...
global___TraceWarningPackage = TraceWarningPackage

class TraceTimeIntervalWarning(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LOCATIONIDHASH_FIELD_NUMBER: builtins.int
    STARTINTERVALNUMBER_FIELD_NUMBER: builtins.int
    PERIOD_FIELD_NUMBER: builtins.int
    TRANSMISSIONRISKLEVEL_FIELD_NUMBER: builtins.int
    locationIdHash: builtins.bytes = ...
    """SHA-256 of the Location ID"""

    startIntervalNumber: builtins.int = ...
    """10-minute intervals since UNIX Epoch"""

    period: builtins.int = ...
    """Number of 10-minute intervals to which the warning applies"""

    transmissionRiskLevel: builtins.int = ...
    def __init__(self,
        *,
        locationIdHash : builtins.bytes = ...,
        startIntervalNumber : builtins.int = ...,
        period : builtins.int = ...,
        transmissionRiskLevel : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locationIdHash",b"locationIdHash","period",b"period","startIntervalNumber",b"startIntervalNumber","transmissionRiskLevel",b"transmissionRiskLevel"]) -> None: ...
global___TraceTimeIntervalWarning = TraceTimeIntervalWarning
